# Generated by Django 6.0.3 on 2026-03-31 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Cuốn sách', 'verbose_name_plural': 'Danh sách Sách'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Thể loại', 'verbose_name_plural': 'Danh mục Thể loại'},
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Ảnh bìa minh họa'),
        ),
        migrations.AlterField(
            model_name='book',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng sẵn có'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category', verbose_name='Thể loại'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả sách'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Năm xuất bản'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhà xuất bản'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề sách'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Tổng số lượng'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên thể loại'),
        ),
        migrations.AlterField(
            model_name='category',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
    ]
